site_name: ExtremeWeatherBench
site_url: https://extremeweatherbench.readthedocs.io/
site_author: Brightband PBC
repo_url: https://github.com/brightbandtech/extremeweatherbench
repo_name: brightbandtech/extremeweatherbench

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Data: data.md
  - Data Preparation: data_prep.md
  - A Note on Parallelism: parallelism.md
  - Case Studies:
      - Overview: events/case_studies.md
      - Atmospheric Rivers: events/atmospheric_rivers.md
      - Severe Convection: events/severe_convection.md
      - Freezes: events/cold_snaps.md
      - Heat Waves: events/heat_waves.md
      - Tropical Cyclones: events/tropical_cyclones.md
      - Planned Event Types: events/planned_events.md
  - Cookbook:
      - CIRA Forecast: recipes/cira_forecast.md
      - BYOF (Bring Your Own Forecast): recipes/your_own_forecast.md
      - BYOT (Bring Your Own Target): recipes/your_own_target.md
      - BYOM (Bring Your Own Metrics): recipes/your_own_metrics.md
      - BYOV (Bring Your Own Variable): recipes/your_own_variable.md
      - Evaluate Recent Tropical Cyclones: recipes/evaluate_recent_tropical_cyclones.md
      - Near Real-Time Point Observations: recipes/near_real_time_point_observations.md
      - Single Case: recipes/single_case.md
      - One Forecast, Two Targets: recipes/one_forecast_two_targets.md
      - Multi Model Evaluation: recipes/multi_model_evaluation.md

theme:
  name: material
  logo: _static/bb_dark.svg
  favicon: _static/bb_dark.svg
  palette:
    scheme: "brightband"

extra_css:
  - stylesheets/brightband.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - search
  - mkdocs-autoapi:
      autoapi_dir: src/extremeweatherbench
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            group_by_category: true
            # show_category_heading: true
            docstring_section_style: list
            show_source: false
            separate_signature: true
            signature_crossrefs: true
            summary: true
