"""ExtremeWeatherBench: A benchmarking framework for extreme weather forecasts.

This module provides the public API for ExtremeWeatherBench. Users can import
the package and access all key functionality:

    import extremeweatherbench as ewb

    # Main entry point for evaluation
    ewb.evaluation(case_metadata=..., evaluation_objects=...)

    # Hierarchical access via namespace submodules
    ewb.targets.ERA5(...)
    ewb.forecasts.ZarrForecast(...)
    ewb.metrics.MeanAbsoluteError(...)

    # Also available at top level
    ewb.ERA5(...)
    ewb.load_cases()
"""

from types import SimpleNamespace

from extremeweatherbench.calc import (
    convert_from_cartesian_to_latlon,
    geopotential_thickness,
    great_circle_mask,
    haversine_distance,
    maybe_calculate_wind_speed,
    mixing_ratio,
    orography,
    pressure_at_surface,
    saturation_mixing_ratio,
    saturation_vapor_pressure,
    specific_humidity_from_relative_humidity,
)
from extremeweatherbench.cases import (
    CaseOperator,
    IndividualCase,
    build_case_operators,
    load_ewb_events_yaml_into_case_list,
    load_individual_cases,
    load_individual_cases_from_yaml,
    read_incoming_yaml,
)
from extremeweatherbench.defaults import (
    DEFAULT_COORDINATE_VARIABLES,
    DEFAULT_VARIABLE_NAMES,
    cira_atmospheric_river_forecast,
    cira_freeze_forecast,
    cira_heatwave_forecast,
    cira_severe_convection_forecast,
    cira_tropical_cyclone_forecast,
    era5_atmospheric_river_target,
    era5_freeze_target,
    era5_heatwave_target,
    get_brightband_evaluation_objects,
    get_climatology,
    ghcn_freeze_target,
    ghcn_heatwave_target,
    ibtracs_target,
    lsr_target,
    pph_target,
)
from extremeweatherbench.derived import (
    AtmosphericRiverVariables,
    CravenBrooksSignificantSevere,
    DerivedVariable,
    TropicalCycloneTrackVariables,
    maybe_derive_variables,
    maybe_include_variables_from_derived_input,
)
from extremeweatherbench.evaluate import ExtremeWeatherBench
from extremeweatherbench.inputs import (
    ARCO_ERA5_FULL_URI,
    DEFAULT_GHCN_URI,
    ERA5,
    GHCN,
    IBTRACS_URI,
    LSR,
    LSR_URI,
    PPH,
    PPH_URI,
    CIRA_metadata_variable_mapping,
    ERA5_metadata_variable_mapping,
    EvaluationObject,
    ForecastBase,
    HRES_metadata_variable_mapping,
    IBTrACS,
    IBTrACS_metadata_variable_mapping,
    InputBase,
    KerchunkForecast,
    TargetBase,
    XarrayForecast,
    ZarrForecast,
    align_forecast_to_target,
    check_for_missing_data,
    maybe_subset_variables,
    open_kerchunk_reference,
    zarr_target_subsetter,
)
from extremeweatherbench.metrics import (
    Accuracy,
    BaseMetric,
    CompositeMetric,
    CriticalSuccessIndex,
    DurationMeanError,
    EarlySignal,
    FalseAlarmRatio,
    FalseNegatives,
    FalsePositives,
    LandfallDisplacement,
    LandfallIntensityMeanAbsoluteError,
    LandfallMetric,
    LandfallTimeMeanError,
    MaximumLowestMeanAbsoluteError,
    MaximumMeanAbsoluteError,
    MeanAbsoluteError,
    MeanError,
    MeanSquaredError,
    MinimumMeanAbsoluteError,
    RootMeanSquaredError,
    SpatialDisplacement,
    ThresholdMetric,
    TrueNegatives,
    TruePositives,
)
from extremeweatherbench.regions import (
    REGION_TYPES,
    BoundingBoxRegion,
    CenteredRegion,
    Region,
    RegionSubsetter,
    ShapefileRegion,
    map_to_create_region,
    subset_cases_to_region,
    subset_results_to_region,
)
from extremeweatherbench.utils import (
    check_for_vars,
    convert_day_yearofday_to_time,
    convert_init_time_to_valid_time,
    convert_longitude_to_180,
    convert_longitude_to_360,
    convert_valid_time_to_init_time,
    derive_indices_from_init_time_and_lead_time,
    determine_temporal_resolution,
    extract_tc_names,
    filter_kwargs_for_callable,
    find_common_init_times,
    idx_to_coords,
    interp_climatology_to_target,
    is_valid_landfall,
    load_land_geometry,
    maybe_cache_and_compute,
    maybe_densify_dataarray,
    maybe_get_closest_timestamp_to_center_of_valid_times,
    maybe_get_operator,
    min_if_all_timesteps_present,
    min_if_all_timesteps_present_forecast,
    read_event_yaml,
    remove_ocean_gridpoints,
    stack_dataarray_from_dims,
)

calc = SimpleNamespace(
    geopotential_thickness=geopotential_thickness,
    specific_humidity_from_relative_humidity=specific_humidity_from_relative_humidity,
    convert_from_cartesian_to_latlon=convert_from_cartesian_to_latlon,
    great_circle_mask=great_circle_mask,
    maybe_calculate_wind_speed=maybe_calculate_wind_speed,
    mixing_ratio=mixing_ratio,
    orography=orography,
    pressure_at_surface=pressure_at_surface,
    saturation_mixing_ratio=saturation_mixing_ratio,
    saturation_vapor_pressure=saturation_vapor_pressure,
    haversine_distance=haversine_distance,
)

# Aliases
evaluation = ExtremeWeatherBench
load_cases = load_ewb_events_yaml_into_case_list

# Namespace submodules
targets = SimpleNamespace(
    TargetBase=TargetBase,
    ERA5=ERA5,
    GHCN=GHCN,
    IBTrACS=IBTrACS,
    LSR=LSR,
    PPH=PPH,
)

forecasts = SimpleNamespace(
    ForecastBase=ForecastBase,
    ZarrForecast=ZarrForecast,
    KerchunkForecast=KerchunkForecast,
    XarrayForecast=XarrayForecast,
)

metrics = SimpleNamespace(
    BaseMetric=BaseMetric,
    CompositeMetric=CompositeMetric,
    ThresholdMetric=ThresholdMetric,
    LandfallMetric=LandfallMetric,
    MeanSquaredError=MeanSquaredError,
    MeanAbsoluteError=MeanAbsoluteError,
    MeanError=MeanError,
    RootMeanSquaredError=RootMeanSquaredError,
    CriticalSuccessIndex=CriticalSuccessIndex,
    FalseAlarmRatio=FalseAlarmRatio,
    Accuracy=Accuracy,
    TruePositives=TruePositives,
    FalsePositives=FalsePositives,
    TrueNegatives=TrueNegatives,
    FalseNegatives=FalseNegatives,
    EarlySignal=EarlySignal,
    MaximumMeanAbsoluteError=MaximumMeanAbsoluteError,
    MinimumMeanAbsoluteError=MinimumMeanAbsoluteError,
    MaximumLowestMeanAbsoluteError=MaximumLowestMeanAbsoluteError,
    DurationMeanError=DurationMeanError,
    SpatialDisplacement=SpatialDisplacement,
    LandfallDisplacement=LandfallDisplacement,
    LandfallTimeMeanError=LandfallTimeMeanError,
    LandfallIntensityMeanAbsoluteError=LandfallIntensityMeanAbsoluteError,
)

cases = SimpleNamespace(
    IndividualCase=IndividualCase,
    CaseOperator=CaseOperator,
    build_case_operators=build_case_operators,
    load_individual_cases=load_individual_cases,
    load_individual_cases_from_yaml=load_individual_cases_from_yaml,
    load_ewb_events_yaml_into_case_list=load_ewb_events_yaml_into_case_list,
    read_incoming_yaml=read_incoming_yaml,
)

derived = SimpleNamespace(
    DerivedVariable=DerivedVariable,
    TropicalCycloneTrackVariables=TropicalCycloneTrackVariables,
    CravenBrooksSignificantSevere=CravenBrooksSignificantSevere,
    AtmosphericRiverVariables=AtmosphericRiverVariables,
    maybe_derive_variables=maybe_derive_variables,
    maybe_include_variables_from_derived_input=maybe_include_variables_from_derived_input,
)

regions = SimpleNamespace(
    Region=Region,
    CenteredRegion=CenteredRegion,
    BoundingBoxRegion=BoundingBoxRegion,
    ShapefileRegion=ShapefileRegion,
    RegionSubsetter=RegionSubsetter,
    REGION_TYPES=REGION_TYPES,
    map_to_create_region=map_to_create_region,
    subset_cases_to_region=subset_cases_to_region,
    subset_results_to_region=subset_results_to_region,
)

defaults = SimpleNamespace(
    DEFAULT_COORDINATE_VARIABLES=DEFAULT_COORDINATE_VARIABLES,
    DEFAULT_VARIABLE_NAMES=DEFAULT_VARIABLE_NAMES,
    get_climatology=get_climatology,
    get_brightband_evaluation_objects=get_brightband_evaluation_objects,
    era5_heatwave_target=era5_heatwave_target,
    era5_freeze_target=era5_freeze_target,
    era5_atmospheric_river_target=era5_atmospheric_river_target,
    ghcn_heatwave_target=ghcn_heatwave_target,
    ghcn_freeze_target=ghcn_freeze_target,
    lsr_target=lsr_target,
    pph_target=pph_target,
    ibtracs_target=ibtracs_target,
    cira_heatwave_forecast=cira_heatwave_forecast,
    cira_freeze_forecast=cira_freeze_forecast,
    cira_tropical_cyclone_forecast=cira_tropical_cyclone_forecast,
    cira_atmospheric_river_forecast=cira_atmospheric_river_forecast,
    cira_severe_convection_forecast=cira_severe_convection_forecast,
)

utils = SimpleNamespace(
    maybe_get_operator=maybe_get_operator,
    find_common_init_times=find_common_init_times,
    is_valid_landfall=is_valid_landfall,
    load_land_geometry=load_land_geometry,
    maybe_cache_and_compute=maybe_cache_and_compute,
    maybe_densify_dataarray=maybe_densify_dataarray,
    maybe_get_closest_timestamp_to_center_of_valid_times=maybe_get_closest_timestamp_to_center_of_valid_times,
    min_if_all_timesteps_present=min_if_all_timesteps_present,
    min_if_all_timesteps_present_forecast=min_if_all_timesteps_present_forecast,
    determine_temporal_resolution=determine_temporal_resolution,
    convert_init_time_to_valid_time=convert_init_time_to_valid_time,
    convert_valid_time_to_init_time=convert_valid_time_to_init_time,
    convert_day_yearofday_to_time=convert_day_yearofday_to_time,
    interp_climatology_to_target=interp_climatology_to_target,
    check_for_vars=check_for_vars,
    idx_to_coords=idx_to_coords,
    extract_tc_names=extract_tc_names,
    stack_dataarray_from_dims=stack_dataarray_from_dims,
    convert_longitude_to_360=convert_longitude_to_360,
    convert_longitude_to_180=convert_longitude_to_180,
    derive_indices_from_init_time_and_lead_time=derive_indices_from_init_time_and_lead_time,
    filter_kwargs_for_callable=filter_kwargs_for_callable,
    remove_ocean_gridpoints=remove_ocean_gridpoints,
    read_event_yaml=read_event_yaml,
)
__all__ = [
    "evaluation",
    "ExtremeWeatherBench",
    "targets",
    "forecasts",
    "metrics",
    "cases",
    "derived",
    "regions",
    "load_cases",
    "IndividualCase",
    "CaseOperator",
    "build_case_operators",
    "load_individual_cases",
    "load_individual_cases_from_yaml",
    "load_ewb_events_yaml_into_case_list",
    "read_incoming_yaml",
    "InputBase",
    "ForecastBase",
    "TargetBase",
    "EvaluationObject",
    "ZarrForecast",
    "KerchunkForecast",
    "XarrayForecast",
    "ERA5",
    "GHCN",
    "IBTrACS",
    "LSR",
    "PPH",
    "ERA5_metadata_variable_mapping",
    "CIRA_metadata_variable_mapping",
    "HRES_metadata_variable_mapping",
    "IBTrACS_metadata_variable_mapping",
    "ARCO_ERA5_FULL_URI",
    "DEFAULT_GHCN_URI",
    "LSR_URI",
    "PPH_URI",
    "IBTRACS_URI",
    "open_kerchunk_reference",
    "zarr_target_subsetter",
    "align_forecast_to_target",
    "maybe_subset_variables",
    "check_for_missing_data",
    "BaseMetric",
    "CompositeMetric",
    "ThresholdMetric",
    "LandfallMetric",
    "MeanSquaredError",
    "MeanAbsoluteError",
    "MeanError",
    "RootMeanSquaredError",
    "CriticalSuccessIndex",
    "FalseAlarmRatio",
    "Accuracy",
    "TruePositives",
    "FalsePositives",
    "TrueNegatives",
    "FalseNegatives",
    "EarlySignal",
    "MaximumMeanAbsoluteError",
    "MinimumMeanAbsoluteError",
    "MaximumLowestMeanAbsoluteError",
    "DurationMeanError",
    "SpatialDisplacement",
    "LandfallDisplacement",
    "LandfallTimeMeanError",
    "LandfallIntensityMeanAbsoluteError",
    "DerivedVariable",
    "TropicalCycloneTrackVariables",
    "CravenBrooksSignificantSevere",
    "AtmosphericRiverVariables",
    "maybe_derive_variables",
    "maybe_include_variables_from_derived_input",
    "Region",
    "CenteredRegion",
    "BoundingBoxRegion",
    "ShapefileRegion",
    "RegionSubsetter",
    "REGION_TYPES",
    "map_to_create_region",
    "subset_cases_to_region",
    "subset_results_to_region",
    "defaults",
    "DEFAULT_COORDINATE_VARIABLES",
    "DEFAULT_VARIABLE_NAMES",
    "get_climatology",
    "get_brightband_evaluation_objects",
    "era5_heatwave_target",
    "era5_freeze_target",
    "era5_atmospheric_river_target",
    "ghcn_heatwave_target",
    "ghcn_freeze_target",
    "lsr_target",
    "pph_target",
    "ibtracs_target",
    "cira_heatwave_forecast",
    "cira_freeze_forecast",
    "cira_tropical_cyclone_forecast",
    "cira_atmospheric_river_forecast",
    "cira_severe_convection_forecast",
]
